### ISSUE TITLE
Delete Problem

### ISSUE THREAD

**Issue by umitseremet** [uu64/ecs-bg-deployment-example#1]
Hi,

Thanks for the templates you have shared. I have şmplemented and it works without a problem but during cleaning, while pipeline-stack is cleaned without any problem the TemplateConfiguration related stack can not be cleaned and it becomes a hanged stack although I have regenerated the deleted cloud formation role. So, how do you handle cleaning operations for all created components?  I have experienced 1 delete command can not delete both of them a the same time, firstly TemplateConfiguration related stack then the left main pipeline-stack needs to be deleted. Is there any way to delete both of them with a single command?

Thanks

**Comment by uu64** [comment]
Hi, @umitseremet 

Do you mean that you deleted the IAM role you specified when creating the CloudFormation stack first, and then tried to delete the stack, and an error occurred?

In my case, I followed the steps below to create and delete the stack, and the error did not occur.

- Create the IAM roles required for CloudFormation and AWS CodeFamily in advance.
- Create the application and pipeline stacks as described in the README
- Delete the application and pipeline stacks (manually from the management console)
- Delete the pre-created IAM roles.

 I think it would be difficult to delete all related resources including IAM roles with a single command.

I hope this helps!

**Comment by umitseremet** [comment]
I see, thanks for the clarification, and thanks for the sharing.
